// AnkiFruit — generates the HTTP method routing table from Anki's protobuf
// descriptor pool.
//
// Anki dispatches every backend call through
// `Backend::run_service_method(service: u32, method: u32, input: &[u8])`.
// The two indices are assigned by `anki_proto_gen::get_services()`. Upstream is
// explicit that clients must use the `.index` fields it returns rather than
// recomputing them by enumeration, so that is what we do here.

use std::env;
use std::fs;
use std::path::PathBuf;

use anki_proto_gen::descriptors_path;
use anki_proto_gen::get_services;
use anyhow::Result;
use prost_reflect::DescriptorPool;

/// `Method::from_proto` stores names already lowered to snake_case; Anki's
/// TypeScript client camel-cases them to build the `/_anki/<method>` path.
fn to_camel_case(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut capitalize = false;
    for ch in snake.chars() {
        if ch == '_' {
            capitalize = true;
        } else if capitalize {
            out.extend(ch.to_uppercase());
            capitalize = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn main() -> Result<()> {
    let descriptors = descriptors_path();
    println!("cargo:rerun-if-changed={}", descriptors.display());
    println!("cargo:rerun-if-changed=build.rs");

    let pool = DescriptorPool::decode(fs::read(&descriptors)?.as_ref())?;
    let (_col_services, backend_services) = get_services(&pool);

    // (http_name, service_index, method_index, service_name)
    let mut routes: Vec<(String, usize, usize, String)> = Vec::new();
    for service in &backend_services {
        // The frontend service is not dispatched through run_service_method.
        if service.name == "BackendFrontendService" {
            continue;
        }
        for method in service.all_methods() {
            routes.push((
                to_camel_case(&method.name),
                service.index,
                method.index,
                service.name.clone(),
            ));
        }
    }

    // A bare `/_anki/<method>` path is only unambiguous when the method name is
    // unique across services. Ambiguous names stay reachable via the qualified
    // `/_anki/<Service>/<method>` form.
    let mut flat: Vec<&(String, usize, usize, String)> = Vec::new();
    for route in &routes {
        if routes.iter().filter(|r| r.0 == route.0).count() == 1 {
            flat.push(route);
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n\n");
    out.push_str("/// Resolves an unqualified `/_anki/<method>` path.\n");
    out.push_str("pub fn lookup(method: &str) -> Option<(u32, u32)> {\n    Some(match method {\n");
    for (name, svc, mth, _) in &flat {
        out.push_str(&format!("        {name:?} => ({svc}, {mth}),\n"));
    }
    out.push_str("        _ => return None,\n    })\n}\n\n");

    out.push_str("/// Resolves a qualified `/_anki/<Service>/<method>` path.\n");
    out.push_str(
        "pub fn lookup_qualified(service: &str, method: &str) -> Option<(u32, u32)> {\n    Some(match (service, method) {\n",
    );
    for (name, svc, mth, svc_name) in &routes {
        let short = svc_name.trim_start_matches("Backend");
        out.push_str(&format!("        ({short:?}, {name:?}) => ({svc}, {mth}),\n"));
    }
    out.push_str("        _ => return None,\n    })\n}\n\n");

    out.push_str(&format!(
        "/// Every routable method, as `(service_index, method_index, service, method)`.\npub const ROUTES: [(u32, u32, &str, &str); {}] = [\n",
        routes.len()
    ));
    for (name, svc, mth, svc_name) in &routes {
        let short = svc_name.trim_start_matches("Backend");
        out.push_str(&format!("    ({svc}, {mth}, {short:?}, {name:?}),\n"));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR")?).join("routes.rs");
    fs::write(&dest, out)?;

    println!(
        "cargo:warning=ankifruit: generated {} routes ({} unqualified) from {}",
        routes.len(),
        flat.len(),
        descriptors.display()
    );
    Ok(())
}
